# Generated by Django 3.2 on 2022-05-07 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=30)),
                ('usn', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered with country code. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
    ]
